version: '3'
services:
  neo4j:
    image: neo4j:5.13.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_dbms_security_auth__enabled=false
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]

  jupyter:
    build: .  # Esta línea indica que Docker debe construir la imagen a partir del Dockerfile en el directorio actual
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work

volumes:
  neo4j-data:
  neo4j-logs:
  notebooks:

